name: Run Gradle integration test

on:
  workflow_dispatch:

jobs:
  gradle-test-integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: gradle/gradle-build-action@v3
      name: Setup Gradle
      id: setup-gradle
    - name: gradle integration test
      id: gradle
      run: ./gradlew -PenvIsCi=true testIntegration
      env:
        DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
    - name: "Add Build Scan URL to summary"
      if: always() && steps.gradle.outputs.build-scan-url != ''
      run: |
        echo "### Gradle Build Scan" >> $GITHUB_STEP_SUMMARY
        echo "${{ steps.gradle.outputs.build-scan-url }}" >> $GITHUB_STEP_SUMMARY
